version: "3.9"
services:
  mysql:
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ui-trade
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  minio:
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    command: ["server", "/data", "--console-address", ":9090"]
    volumes:
      - "minio:/data"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ACCESS_KEY=accsess_key
      - MINIO_SECRET_KEY=secret_key
    ports:
      - "9000:9000"
      - "9090:9090"
  createbuckets:
    image: minio/mc:RELEASE.2022-12-24T15-21-38Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set ui-trade http://minio:9000 root password;
      until mc ls ui-trade; do echo '...waiting...' && sleep 1; done;
      mc mb --ignore-existing ui-trade/ui-trade-private;
      mc mb --ignore-existing ui-trade/ui-trade-public;
      mc mb --ignore-existing ui-trade/ui-trade-preview;
      mc anonymous set download ui-trade/ui-trade-public;
      mc anonymous set private ui-trade/ui-trade-private;
      mc policy set download ui-trade/ui-trade-preview;
      "

volumes:
  mysql:
  minio:
