version: "3.9"
services:
  minio-test:
    image: minio/minio:latest
    command: ["server", "/data", "--console-address", ":9090"]
    volumes:
      - "minio-test:/data"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
      - MINIO_ACCESS_KEY=accsess_key
      - MINIO_SECRET_KEY=secret_key
    ports:
      - "7777:9000"
      - "9999:9090"
  createbuckets-test:
    image: minio/mc:latest
    depends_on:
      - minio-test
    entrypoint: >
      /bin/sh -c "
      mc alias set ui-trade-test http://minio-test:9000 root password;
      until mc ls ui-trade-test; do echo '...waiting...' && sleep 5; done;
      mc mb --ignore-existing ui-trade-test/ui-trade-private;
      mc mb --ignore-existing ui-trade-test/ui-trade-public;
      mc mb --ignore-existing ui-trade-test/ui-trade-preview;
      mc anonymous set download ui-trade-test/ui-trade-public;
      mc anonymous set private ui-trade-test/ui-trade-private;
      mc anonymous set download ui-trade-test/ui-trade-preview;
      "

volumes:
  minio-test:
