import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@/style/tailwind.css";
import { Toaster } from "@/components/ui/toaster";
import { BaseLayout } from "@/layouts/root";
import { cn } from "@/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = "false";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <BaseLayout>{children}</BaseLayout>
        <Toaster />
      </body>
    </html>
  );
}
