name: Run unit Tests

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # services:
    #   mysql:
    #     image: mysql:8.0.35
    #     env:
    #       MYSQL_ROOT_PASSWORD: root
    #       MYSQL_DATABASE: ui-trade-test
    #       MYSQL_USER: user
    #       MYSQL_PASSWORD: password
    #       TZ: "Asia/Tokyo"
    #     ports:
    #       - 3306:3306

    #     options: --health-cmd="mysqladmin ping"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=3
    #   minio:
    #     image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    #     env:
    #       MINIO_ROOT_USER: root
    #       MINIO_ROOT_PASSWORD: password
    #       MINIO_ACCESS_KEY: accsess_key
    #       MINIO_SECRET_KEY: secret_key
    #     ports:
    #       - 9000:9000
    #       - 9090:9090

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.7.4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Docker Compose
        run: docker-compose -f docker-compose.test.yaml up -d

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup environment variables
        run: cp .env.example.test .env.test

      - name: Run tests
        run: pnpm test
